const Experience = () => {
    return (
        <div className="experience" id="experience">
            <div className="experience-container">
                <h1 className="reveal">Experience</h1>

                <h2 className="reveal">Internships</h2>
                <div className="experience-card-holder-internship reveal-group">

                    <div className="experience-card coral-2">
                        <h2>Universal Orlando Resort</h2>
                        <h3>Advanced Capabilities & Architecture Intern</h3>
                        <p>   
                            Incoming Fall 2026 – will focus on AI initiatives, emerging technology, and cross-team collaboration across Park Operations, Digital & Technology, and Food & Beverage.

                        </p>
                    </div>

                    <div className="experience-card coral-2">
                        <h2>NextEra Energy</h2>
                        <h3>Software Development Engineer Intern</h3>
                        <p>
                            Assigned an epic on NextVision, an internal platform that visualizes drone-captured imagery and infrastructure data at scale, built on top of Atlas, NextEra's image ingestion and processing system.
                        </p>
                        <ul>
                            <li>
                                Engineered a pipeline that extracted asset and condition detections from Raw Annotation Files generated by multiple AI models, translated them into business-facing labels, and synced that data from PostgreSQL into OpenSearch, including handling updates and deletes to prevent stale data, enabling a single API call to filter both assets and AI-detected conditions together.
                            </li>
                            <li>
                                Built the corresponding filtering and search UI in NextVision using React and TypeScript, including advanced filter menus and shareable deep links in data exports.
                            </li>
                            <li>
                                Wrote unit and end-to-end tests, and worked through full Agile sprint cycles from planning through deployment.
                            </li>
                        </ul>
                    </div>

                    <div className="experience-card coral-2">
                        <h2>Universal Orlando Resort</h2>
                        <h3>Software Quality Engineering Intern</h3>
                        <p>
                            Worked on the Mobile QE team, with a mentor supporting my ramp-up, and gained exposure to other QE areas across web, eCommerce, and physical park systems.
                        </p>
                        <ul>
                            <li>
                                Extended and maintained mobile automation frameworks to validate new app updates across Orlando, California, and Japan properties, using Java, Python, Selenium, and Appium to catch regressions before release.
                            </li>
                            <li>
                                Developed and executed test plans for web and eCommerce platforms, including cross-browser and cross-device validation using LambdaTest.
                            </li>
                            <li>
                                Gained exposure to physical testing of in-park technology and hardware through Universal's QA Lab, alongside software QE work.
                            </li>
                        </ul>
                    </div>


                    <div className="experience-card coral-2">
                        <h2>NextEra Energy</h2>
                        <h3>Programmer Analyst Intern</h3>
                        <p>
                            Joined the API Catalog project, a new initiative to centralize NextEra's 18,000+ internal nuclear APIs and proposed adding an AI-powered search feature to replace manual API lookup.
                        </p>
                        <ul>
                            <li>
                                Built an AI assistant (Angular, TypeScript, Flask, Python, OpenAI LLMs) that interprets natural language requests and identifies the most relevant APIs, reviewing and refining API documentation across the catalog to ensure the model had enough context to match queries accurately.
                            </li>
                            <li>
                                Identified that the existing Angular codebase was difficult to maintain and led a refactor of the front-end architecture, including state management and routing, to simplify the system and support long-term scalability.
                            </li>
                            <li>
                                Presented the finished platform to the director and nuclear development team, who adopted it as the foundation for NextEra's nuclear IT development standards, with plans to extend it with Splunk-based utilization monitoring.
                            </li>
                        </ul>
                    </div>
                    <div className="experience-card coral-2">
                        <h2>NextEra Energy</h2>
                        <h3>Nuclear Solutions Analyst Intern</h3>
                        <p>
                            Worked with NextEra's Nuclear Innovation team exploring emerging technology applications at the St. Lucie Nuclear Power Plant.
                        </p>
                        <ul>
                            <li>
                                Built autonomous patrol routes for robotic quadrupeds at St. Lucie using a route-mapping platform, working alongside a team to develop timed inspection pathways for automated facility monitoring.
                            </li>
                            <li>
                                Presented the robotics patrol project to regional Nuclear Regulatory Commission directors, contributing to their support for automation in nuclear facility inspections.
                            </li>
                            <li>
                                Independently researched and built a VR proof-of-concept control room prototype using Unity and Meta Quest, incorporating LiDAR-based 3D environments, to explore virtual operator training as an alternative to in-person site visits.
                            </li>
                        </ul>
                    </div>
                    <div className="experience-card coral-2">
                        <h2>Sparton Corporation</h2>
                        <h3>Acoustic Engineering Intern</h3>
                        <p>
                            Identified a testing bottleneck in sonobuoy production causing delays and workers being sent home early, and led the initiative to solve it using skills from my first year of computer science coursework.
                        </p>
                        <ul>
                            <li>
                                Led the project across problem identification, requirements gathering, implementation, and deployment, coordinating with multiple departments and customizing existing impedance analyzer driver code in C, with guidance from a senior engineer, to eliminate the need for an advanced operator to run manual tests.
                            </li>
                            <li>
                                Integrated the automated test station with a SQL Server database to store test results, reducing testing cycle time for piezoelectric ceramic components from 160 seconds to 40 seconds and restoring full capacity for the line.
                            </li>
                            <li>
                                Supported sonobuoy production through test data analysis, calculations, and documentation used by engineers for quality control.
                            </li>
                        </ul>
                    </div>
                </div>

                <h2 className="reveal">Mentorships</h2>
                <div className="experience-card-holder-mentorship reveal-group">
                    <div className="experience-card coral-2a">
                        <h2>Amazon Robotics</h2>
                        <h3>Amazon Guides Mentee</h3>
                        <p>
                            Selected for a structured mentorship program pairing students with Amazon engineering leadership for weekly technical sessions on large-scale systems.
                        </p>
                        <ul>
                            <li>
                                Studied fulfillment center robotics architecture and workcell automation, including how operations scale during seasonal demand spikes.
                            </li>
                            <li>
                                Worked with an engineering mentor to understand Amazon's full engineering lifecycle, from problem discovery to maintaining production deployment at 99.9% uptime.
                            </li>
                        </ul>
                    </div>
                </div>

                <h2 className="reveal">Community</h2>
                <div className="experience-card-holder-leadership reveal-group">
                    <div className="experience-card coral-2b">
                        <h2>South Florida Tech Hub</h2>
                        <h3>Instructional Coder</h3>
                        <p>
                            Volunteered monthly to teach K-12 students fundamental programming concepts using Code.org and freeCodeCamp.
                        </p>
                        <p>
                            Guided students through problem-solving when they got stuck, tailoring resources and support to each student's skill level.
                        </p>
                    </div>
                </div>

            </div>
        </div>
    )
}

export default Experience
